# Generated by Django 2.2 on 2019-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='picture',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
