# Generated by Django 2.2 on 2019-06-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_data_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='avgCommentsRatio',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='data',
            name='avgLikesRatio',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AddField(
            model_name='data',
            name='followerCount',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
